-- CREATE DATABASE

CREATE DATABASE todolist;

-- CREATE TABLE

CREATE TABLE todo(
  todo_id SERIAL PRIMARY KEY,
  description VARCHAR(255)
);

-- ADD COLUMN TO THE TABLE

ALTER TABLE todo ADD completed BOOLEAN NOT NULL DEFAULT false;


CREATE TABLE user(
  todo_id SERIAL PRIMARY KEY,
  description VARCHAR(255)
);

